### PR TITLE
Project structure refactor

### PR DESCRIPTION
**Pull request by jeparlefrancais**
## Things I've done:

- move common spec files into a `common-spec` folder, so they are not duplicated anymore
- the `try` test framework was de-duplicated too
- run selene on src/roblox and src/vanilla (we could probably add a specific config for vanilla if there is a 5.2 lua std)
- put rojo files into a folder in the root of the project: one for the library and one for the test place
- added a `scripts` directory that contains commands to run scripts for both the roblox version and lua version

## Questions

- is `testBase.lua` used? If not I suggest we clean it up 😄 
- should we move the benchmarking scripts into the `scripts` folder? I am not sure how they are currently runnable (my goal would be to only have the spec files directly into `roblox-tests`, without mixing them with the other current ones)

Let me know if this structure fits you, or if I can do any other improvements

Thanks again for this great library! 🎉

### CODE REVIEW

**Comment by Dekkonot** [comment]
I don't have the time tonight to fully review the changes but to answer you question:
 - I use `testBase.lua` for copy and pasting new test files... Probably a better way to do it but that's how I'm doing it
 - Benchmarks are run using [BoatBomber's benchmarker plugin](https://devforum.roblox.com/t/benchmarker-plugin-compare-function-speeds-with-graphs-percentiles-and-more/829912). I should document that in the readme or in a contributing guideline but they're a relatively new addition so I haven't gotten around to it yet.

Overall I'm open to these changes though. I'll do a more thorough review in the next few days (remind me if I don't!).

**Comment by Dekkonot** [comment]
That said, it seems that at some point Kampfkarren moved the download location for Selene, so we should probably fix that before this gets merge, haha.

**Comment by jeparlefrancais** [comment]
> 
> 
> That said, it seems that at some point Kampfkarren moved the download location for Selene, so we should probably fix that before this gets merge, haha.

Do you want to use foreman? I can set that up if you want to

**Comment by Dekkonot** [comment]
> > That said, it seems that at some point Kampfkarren moved the download location for Selene, so we should probably fix that before this gets merge, haha.
> 
> Do you want to use foreman? I can set that up if you want to

It seems a bit overkill to use Foreman for one tool IMO. I would rather just clone it manually.

**Comment by jeparlefrancais** [comment]
> 
> It seems a bit overkill to use Foreman for one tool IMO. I would rather just clone it manually.

Foreman is also great for contributors, since they can run one command and have the right version locally for your project. Plus it avoids having to fix your CI when Kampfkarren move stuff around 😆 And it'll be there if you ever want to add another tool (you could get rojo with foreman too)

But I get your reasons too, so I'm good with what you prefer. 

And thanks for your comments, I'll go ahead and make some tweaks probably tomorrow, I'll ping you when that's done

**Comment by Dekkonot** [comment]
After taking a closer look, I think we should move the spec files + `try.lua` into a dedicated `tests` folder; it can be inside of `src` if you want but having them in a folder would be better IMO.

Additionally we can go ahead and just remove `roblox` and `vanilla` folders if they're just going to have an `init.lua` in them. Instead of `roblox/init.lua` and `vanilla/init.lua` we can just have `roblox.lua` and `vanilla.lua`.

We should also probably find a better home for benchmarks files, since as-is they're just kind of there. Maybe in a `benchmarks` folder?

These changes would leave us with a file tree that looked basically like:
```plaintext
- src
  - benchmarks
    - vanilla.lua
    - roblox-primitives.lua
    - roblox-structs.lua
  - tests
    - common-spec
    - roblox-spec
    - try.lua
  - roblox.lua
  - vanilla.lua
```

I'm open to better suggestions though. The benchmarks can always live in the test folder if we don't have a good solution.

**Comment by jeparlefrancais** [comment]
I kept the `roblox` folder even if there is only an init file, because it lets it open for extension or if you want to start putting some functions into a separate file. That could make it easier to navigate for new contributors, what do you prefer?

**Comment by Dekkonot** [comment]
I suppose we could put some `selene.toml`s in those, but I'm not using anything in Lua 5.2 that Roblox *doesn't* have (the first part of the Roblox version is literally copy and pasted from the vanilla version) so that seems like a stretch regardless.

As for splitting functions up, that's a no-go for now since it would require an actual refactor of the code (plus I dislike having a bunch of files that have to get copied over for someone to use a module). I'm not saying no to it forever, just not until a refactor happens.

Let's just get rid of the folders for now.

**Comment by Dekkonot** [comment]
Alright, looks good. Thanks!

**Pull request merged**
